/**
 * Built-in example spectra.
 *
 * `shared-data/presets.json` is generated by `scripts/generate_ts_fixtures.py`
 * from the same source data the Python calibration used, already sampled on the
 * canonical descriptor grid.
 */

import presetsJson from '../../shared-data/presets.json';
import { prepareSpectrum } from './spectrum';
import type { PreparedSpectrum } from './spectrum';

interface PresetRecord {
  key: string;
  name: string;
  description: string;
  q: number[];
  reference_density_um3: number;
  reference_a_a0: number;
  descriptors: {
    kp0_um_inv: number;
    delta_k: number;
    w: number;
    c_shape: number;
  };
}

const K_DESC: number[] = presetsJson.metadata.k_desc_um_inv;
const RECORDS = presetsJson.profiles as PresetRecord[];
const DEFAULT_DENSITY_UM3 = 2.8331;
const DEFAULT_A_A0 = 50;

export interface Preset {
  key: string;
  name: string;
  description: string;
  kp_um_inv: number;
  defaultDensity_um3: number;
  defaultA_a0: number;
  load: () => PreparedSpectrum;
}

/**
 * Generated fixtures live on the complete descriptor grid. Measured profiles
 * that started at finite k were historically padded with leading zeroes,
 * erasing the distinction between "unmeasured" and physically empty. Restore
 * the agreed finite low-k occupation: n_k is held at its first measured value,
 * hence the shell distribution q = N_k/N grows as k² toward that point.
 */
function restoreFiniteLowKOccupation(qInput: number[]): number[] {
  const q = qInput.slice();
  const first = q.findIndex((value) => Number.isFinite(value) && value > 0);
  if (first <= 0) return q;
  const k0 = K_DESC[first];
  const q0 = q[first];
  for (let index = 0; index < first; index++) {
    const ratio = K_DESC[index] / k0;
    q[index] = q0 * ratio * ratio;
  }
  return q;
}

const fixturePresets: Preset[] = RECORDS.map((rec) => ({
  key: rec.key,
  name: rec.name,
  description: rec.description,
  kp_um_inv: rec.descriptors.kp0_um_inv,
  defaultDensity_um3: rec.reference_density_um3,
  defaultA_a0: rec.reference_a_a0,
  load: () =>
    prepareSpectrum({
      k_um_inv: K_DESC,
      values: restoreFiniteLowKOccupation(rec.q),
      convention: 'Nk_over_N',
      label: rec.name,
      source: 'preset',
      warnings: [],
    }),
}));

function syntheticPreset({
  key, name, description, convention, values,
}: {
  key: string;
  name: string;
  description: string;
  convention: 'n_k' | 'Nk_over_N';
  values: (k: number) => number;
}): Preset {
  const sampled = K_DESC.map((k) => Math.max(0, values(k)));
  const peakValues = convention === 'n_k'
    ? sampled.map((n, i) => K_DESC[i] * K_DESC[i] * n)
    : sampled;
  let peakIndex = 0;
  for (let i = 1; i < peakValues.length; i++) {
    if (peakValues[i] > peakValues[peakIndex]) peakIndex = i;
  }
  return {
    key,
    name,
    description,
    kp_um_inv: K_DESC[peakIndex],
    defaultDensity_um3: DEFAULT_DENSITY_UM3,
    defaultA_a0: DEFAULT_A_A0,
    load: () => prepareSpectrum({
      k_um_inv: K_DESC,
      values: sampled,
      convention,
      label: name,
      source: 'preset',
      warnings: [],
    }),
  };
}

const preparedState9 = syntheticPreset({
  key: 'prepared_state_9',
  name: 'Prepared State 9',
  description: 'High-wavevector prepared state with a gently skewed tail.',
  convention: 'Nk_over_N',
  values: (k) => {
    const kp = 4.8;
    const sigma = k < kp ? 0.48 : 0.72;
    return Math.exp(-0.5 * ((k - kp) / sigma) ** 2);
  },
});

const exploratoryPresets: Preset[] = [
  syntheticPreset({
    key: 'sharp_gaussian',
    name: 'Sharp Gaussian',
    description: 'Narrow shell distribution centered at k = 2.0 μm⁻¹.',
    convention: 'Nk_over_N',
    values: (k) => Math.exp(-0.5 * ((k - 2) / 0.12) ** 2),
  }),
  syntheticPreset({
    key: 'nk_top_hat',
    name: 'Top-hat in n_k',
    description: 'Heaviside occupation n_k proportional to Θ(k_p - k), with k_p = 2.2 μm⁻¹.',
    convention: 'n_k',
    values: (k) => k < 2.2 ? 1 : 0,
  }),
  syntheticPreset({
    key: 'bose_einstein_mu0',
    name: 'Thermal Bose–Einstein (μ = 0)',
    description: 'Ideal μ = 0 Bose–Einstein occupation with thermal wavevector k_T = 1.5 μm⁻¹.',
    convention: 'n_k',
    values: (k) => 1 / Math.expm1((k / 1.5) ** 2),
  }),
  syntheticPreset({
    key: 'bose_einstein_mu0_perturbed',
    name: 'Thermal + weak perturbation',
    description: 'The μ = 0 thermal state with a weak localized occupation bump near k = 0.55 μm⁻¹.',
    convention: 'n_k',
    values: (k) => {
      const thermal = 1 / Math.expm1((k / 1.5) ** 2);
      const bump = 1 + 0.12 * Math.exp(-0.5 * ((k - 0.55) / 0.1) ** 2);
      return thermal * bump;
    },
  }),
];

const prepared7Index = fixturePresets.findIndex((preset) => preset.key === 'prepared_state_7');
export const PRESETS: Preset[] = [
  ...fixturePresets.slice(0, prepared7Index + 1),
  preparedState9,
  ...fixturePresets.slice(prepared7Index + 1),
  ...exploratoryPresets,
];

export const DEFAULT_PRESET_KEY = 'simon_set_93';

export function getPreset(key: string): Preset {
  return PRESETS.find((p) => p.key === key) ?? PRESETS[0];
}

/** CSV text for a preset, so the user can see and edit the expected format. */
export function presetToCsv(key: string): string {
  const spectrum = getPreset(key).load();
  const lines = [`k_um_inv,${spectrum.raw.convention}`];
  for (let i = 0; i < spectrum.raw.k_um_inv.length; i++) {
    lines.push(`${spectrum.raw.k_um_inv[i].toPrecision(8)},${spectrum.raw.values[i].toPrecision(8)}`);
  }
  return lines.join('\n');
}
