/**
 * Browser-vs-Python cross validation.
 *
 * Every reference number comes from `shared-data/fixtures.json`, generated by
 * `scripts/generate_ts_fixtures.py` from the validated Python solver. Run with
 *
 *     npm test
 *
 * Tolerances are absolute requirements, not descriptions of what happens to
 * pass today: the half-time target is 1%, and the suite fails loudly below it.
 */

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

import { logarithmicGrid, interpolateQ, normalizeQ, trapz } from '../src/physics/grid';
import { leggauss, gaussLegendreLog, interpolationMap } from '../src/physics/quadrature';
import { buildGeometry, collisionComponents, KERNEL_IDS } from '../src/physics/collision';
import { computeScales } from '../src/physics/scales';
import {
  DESCRIPTOR_GRID, computeDescriptors, countModes, peakMomentum, peakMomentumFromF,
} from '../src/physics/descriptors';
import { inferNA, predictDeltaT, shapeFactor, naContour } from '../src/physics/calibration';
import { buildInitialF, runWKE } from '../src/physics/integrator';
import { derivePhysics } from '../src/physics/modes';
import { prepareFromText, prepareSpectrum } from '../src/physics/spectrum';
import { exportTrajectory } from '../src/physics/export';
import { PRESETS } from '../src/physics/presets';
import { SPECIES, BOHR_RADIUS_UM, P_MIN, P_MAX, N_GRID, NQ_LOW, NQ_HIGH, REFERENCE_XI_UM, solverPMax } from '../src/physics/constants';
import type { KernelType } from '../src/physics/collision';

const HERE = dirname(fileURLToPath(import.meta.url));
const load = (name: string) =>
  JSON.parse(readFileSync(resolve(HERE, '..', 'shared-data', name), 'utf8'));

const fixtures = load('fixtures.json');
const META = fixtures.metadata;

// ---------------------------------------------------------------- harness ---

let passed = 0;
const failures: string[] = [];
const rows: string[] = [];

function check(name: string, ok: boolean, detail: string): void {
  if (ok) { passed++; } else { failures.push(`${name}: ${detail}`); }
  rows.push(`${ok ? 'PASS' : 'FAIL'}  ${name.padEnd(52)} ${detail}`);
}

function relClose(name: string, got: number, want: number, tol: number): void {
  const rel = want === 0 ? Math.abs(got) : Math.abs(got - want) / Math.abs(want);
  check(name, rel <= tol, `rel=${rel.toExponential(2)} (tol ${tol.toExponential(1)})`);
}

function absClose(name: string, got: number, want: number, tol: number): void {
  const d = Math.abs(got - want);
  check(name, d <= tol, `|Δ|=${d.toExponential(2)} (tol ${tol.toExponential(1)})`);
}

function section(title: string): void {
  rows.push('', `── ${title} ${'─'.repeat(Math.max(0, 72 - title.length))}`);
}

// ------------------------------------------------------------ quadrature ---

section('Quadrature and interpolation');
{
  // Gauss-Legendre exactness: an n-point rule integrates degree 2n-1 exactly.
  for (const n of [4, 8, 16]) {
    const { x, w } = leggauss(n);
    const deg = 2 * n - 1;
    let got = 0;
    for (let i = 0; i < n; i++) got += w[i] * Math.pow(x[i], deg - 1);
    const want = 2 / (deg - 1 + 1); // ∫_{-1}^{1} x^{2m} dx = 2/(2m+1)
    relClose(`leggauss(${n}) exact to degree ${deg}`, got, want, 1e-13);
  }
  // Weight sum is the interval length.
  const { w } = leggauss(24);
  relClose('leggauss(24) weights sum to 2', w.reduce((a, b) => a + b, 0), 2, 1e-14);

  // log-transformed rule: ∫_a^b dp = b − a
  const { w: lw } = gaussLegendreLog(0.3, 7.5, 16);
  relClose('gaussLegendreLog integrates dp', lw.reduce((a, b) => a + b, 0), 7.5 - 0.3, 1e-10);

  // interpolationMap reproduces linear interpolation in log p
  const grid = logarithmicGrid(0.01, 20, 64);
  const logGrid = Float64Array.from(grid, Math.log);
  const f = Float64Array.from(grid, (p) => 3 * Math.log(p) + 1);
  const probe = 1.234;
  const { idx, alpha } = interpolationMap(logGrid, probe);
  const interpolated = (1 - alpha) * f[idx] + alpha * f[idx + 1];
  relClose('interpolationMap is exact for f linear in log p', interpolated, 3 * Math.log(probe) + 1, 1e-12);
}

// ------------------------------------------------------------------ units ---

section('Units and scales');
{
  relClose('a₀ → μm', 50 * BOHR_RADIUS_UM, 50 * 5.29177210903e-5, 1e-15);
  relClose('a₀ round trip', (137 * BOHR_RADIUS_UM) / BOHR_RADIUS_UM, 137, 1e-14);

  const s = computeScales(META.density_um3, META.scattering_length_a0, SPECIES.K39);
  relClose('ξ matches Python PhysicalScales', s.xi_um, META.xi_um, 1e-12);
  relClose('t₀ matches Python PhysicalScales', s.t0_s, META.t0_s, 1e-12);
  relClose('N_cal matches Python PhysicalScales', s.ncal, META.ncal, 1e-12);
  relClose('na matches Python', s.na_um2, META.na_ref_um2, 1e-12);
  // ξ = 1/√(8π n a) is the closed form the Python property uses.
  relClose('ξ closed form', s.xi_um, 1 / Math.sqrt(8 * Math.PI * META.density_um3 * s.a_um), 1e-12);
  relClose('reference conditions retain canonical p_max', solverPMax(REFERENCE_XI_UM), P_MAX, 1e-14);
  relClose('weak coupling retains reference physical k_max',
    solverPMax(2.5 * REFERENCE_XI_UM) / (2.5 * REFERENCE_XI_UM),
    P_MAX / REFERENCE_XI_UM, 1e-14);
}

// ------------------------------------------------------ collision operator ---

section('Collision operator vs Python');

const pGrid = logarithmicGrid(P_MIN, P_MAX, N_GRID);
const geom = buildGeometry(pGrid, P_MAX / Math.SQRT2, META.ncal, NQ_LOW, NQ_HIGH);
check('event table size matches Python', geom.nEvents === META.n_events,
  `TS=${geom.nEvents} PY=${META.n_events}`);

const kSolver = Float64Array.from(pGrid, (p) => p / META.xi_um);

// The descriptor grid is the solver grid at reference conditions.
{
  let worst = 0;
  for (let i = 0; i < N_GRID; i++) {
    worst = Math.max(worst, Math.abs(DESCRIPTOR_GRID[i] / kSolver[i] - 1));
  }
  check('descriptor grid == reference solver grid', worst < 1e-12, `max rel=${worst.toExponential(2)}`);
}

// ---------------------------------------------------------- descriptors ---

section('Descriptors vs Python');

interface Fixture {
  key: string;
  raw_k: number[];
  raw_q: number[];
  kp0_um_inv: number;
  mean_k_um_inv: number;
  fwhm_um_inv: number;
  delta_k: number;
  w: number;
  c_shape: number;
  A_ref_s_um4: number;
  A_pred_s_um4: number;
  dt_half_classical_s: number;
  dt_half_quantum_s: number;
  trajectory_classical: { t_s: number[]; kp: number[] };
  trajectory_quantum: { t_s: number[]; kp: number[] };
}

const profiles: Fixture[] = fixtures.profiles;

for (const p of profiles) {
  const k = Float64Array.from(p.raw_k);
  const q = Float64Array.from(p.raw_q);
  const d = computeDescriptors(k, q);
  relClose(`${p.key}: ∫q dk = 1`, d.normIntegral, 1, 1e-10);
  relClose(`${p.key}: k_p,0`, d.kp0_um_inv, p.kp0_um_inv, 1e-10);
  relClose(`${p.key}: ⟨k⟩`, d.mean_k_um_inv, p.mean_k_um_inv, 1e-10);
  relClose(`${p.key}: FWHM`, d.fwhm_um_inv, p.fwhm_um_inv, 1e-10);
  absClose(`${p.key}: δ_k`, d.delta_k, p.delta_k, 1e-12);
  relClose(`${p.key}: w`, d.w, p.w, 1e-10);
  relClose(`${p.key}: C_shape`, d.c_shape, p.c_shape, 1e-10);
  relClose(`${p.key}: A_ref = κ k_p²`, d.A_ref_s_um4, p.A_ref_s_um4, 1e-12);
  relClose(`${p.key}: A_pred`, d.A_pred_s_um4, p.A_pred_s_um4, 1e-12);
}

// Presets carry Python descriptors alongside their profiles.
const presets = load('presets.json');
for (const rec of presets.profiles) {
  const prepared = PRESETS.find((x) => x.key === rec.key)!.load();
  const d = computeDescriptors(prepared.k, prepared.q);
  relClose(`preset ${rec.key}: k_p,0`, d.kp0_um_inv, rec.descriptors.kp0_um_inv, 1e-9);
  relClose(`preset ${rec.key}: C_shape`, d.c_shape, rec.descriptors.c_shape, 1e-9);
}
check('canonical analytic preset carries a formula',
  Boolean(PRESETS.find((preset) => preset.key === 'canonical_gaussian')?.formula),
  'expected a typeset definition');
check('curated measured presets suppress import notes',
  ['martin_kick_state', 'nature_2025_p1', 'nature_2025_p2', 'nature_2025_p3'].every(
    (key) => PRESETS.find((preset) => preset.key === key)?.hideImportNotes === true,
  ), 'Martin and Nature P1–P3');

for (const [key, name, points, cutoff] of [
  ['martin_kick_state', 'Martin kick state', 174, 4],
  ['nature_2025_p1', 'Nature 2025: P1', 37, 4],
  ['nature_2025_p2', 'Nature 2025: P2', 39, 4],
  ['nature_2025_p3', 'Nature 2025: P3', 49, 6],
] as const) {
  const preset = PRESETS.find((item) => item.key === key);
  check(`${name} preset is available`, preset != null, key);
  if (preset) {
    const prepared = preset.load();
    check(`${name} retains measured points`, prepared.raw.k_um_inv.length === points,
      `points=${prepared.raw.k_um_inv.length}`);
    check(`${name} obeys its k cutoff`, Math.max(...prepared.raw.k_um_inv) <= cutoff,
      `k_max=${Math.max(...prepared.raw.k_um_inv)}`);
    check(`${name} uses n_k convention`, prepared.raw.convention === 'n_k', prepared.raw.convention);
    check(`${name} produces a nonnegative normalized spectrum`,
      prepared.q.every((value) => value >= 0) && Math.abs(trapz(prepared.q, prepared.k) - 1) < 1e-10,
      `min q=${Math.min(...prepared.q)}`);
  }
}

// --------------------------------------------------------- calibration ---

section('Calibration algebra');
{
  const d = computeDescriptors(
    Float64Array.from(profiles[0].raw_k),
    Float64Array.from(profiles[0].raw_q),
  );
  relClose('C_shape from δ_k, w', shapeFactor(d.delta_k, d.w), d.c_shape, 1e-14);

  // na ↔ Δt inversion must be exact.
  const na = META.na_ref_um2;
  const dt = predictDeltaT(d, na);
  relClose('inferNA(predictDeltaT(na)) == na', inferNA(d, dt), na, 1e-12);

  // Δt scales as (na)⁻².
  relClose('Δt ∝ (na)⁻²', predictDeltaT(d, 2 * na) / dt, 0.25, 1e-12);

  // The C = 1 map contour agrees with the formula stripped of C_shape.
  relClose('naContour == √(κ k_p²/Δt)', naContour(d.kp0_um_inv, dt),
    Math.sqrt(META.kappa_s_um2 * d.kp0_um_inv ** 2 / dt), 1e-14);
  relClose('shape-corrected contour == inferNA', naContour(d.kp0_um_inv, dt) * Math.sqrt(d.c_shape),
    inferNA(d, dt), 1e-12);
}

// ------------------------------------------------------ spectrum import ---

section('Spectrum import conventions');
{
  // n_k convention: N_k = 4π k² n_k, so a flat n_k must produce q ∝ k².
  const lines = ['k_um_inv,n_k'];
  for (let i = 1; i <= 60; i++) lines.push(`${(i * 0.1).toFixed(4)},1.0`);
  const s = prepareFromText(lines.join('\n'), 'n_k', 'flat n_k', 'paste');
  const mid = Math.floor(s.raw.k_um_inv.length / 2);
  const ratio = s.qRaw[mid] / s.qRaw[mid - 1];
  const kRatio = (s.raw.k_um_inv[mid] / s.raw.k_um_inv[mid - 1]) ** 2;
  relClose('n_k convention applies 4π k²', ratio, kRatio, 1e-12);
  check('n_k header detected', s.raw.detectedColumns?.[1] === 'n_k',
    `got ${s.raw.detectedColumns?.join(',')}`);

  // Missing low-k measurements retain the first finite n_k, rather than
  // fabricating a zero-density region before the measurement starts.
  const truncated = prepareSpectrum({
    k_um_inv: [0.1, 0.2, 0.3, 0.4], values: [2, 2, 2, 2],
    convention: 'n_k', label: 'truncated flat n_k', source: 'paste', warnings: [],
  });
  const low = 0;
  const next = 1;
  relClose('missing low-k n_k is held constant',
    truncated.q[low] / truncated.q[next],
    (truncated.k[low] / truncated.k[next]) ** 2, 1e-12);

  const truncatedShell = prepareSpectrum({
    k_um_inv: [0.1, 0.2, 0.3, 0.4], values: [2, 2, 2, 2],
    convention: 'Nk_over_N', label: 'truncated shell data', source: 'paste', warnings: [],
  });
  relClose('missing low-k shell data also preserves finite n_k',
    truncatedShell.q[low] / truncatedShell.q[next],
    (truncatedShell.k[low] / truncatedShell.k[next]) ** 2, 1e-12);

  const simon = PRESETS.find((preset) => preset.key === 'simon_set_93')!.load();
  const simonOccupation0 = simon.q[0] / (simon.k[0] * simon.k[0]);
  const simonOccupation1 = simon.q[1] / (simon.k[1] * simon.k[1]);
  relClose('Simon padded low-k region restores finite n_k', simonOccupation0, simonOccupation1, 1e-12);

  // Moving from the descriptor grid to a run-specific physical grid must not
  // introduce empty low-k cells. Infer the regular low-k power law instead.
  const shiftedLowGrid = Float64Array.from([0.025, 0.05, 0.1]);
  const finiteOccupationQ = interpolateQ(
    [0.1, 0.2, 0.3], [0.01, 0.04, 0.09], shiftedLowGrid, { lower: 'power-law' },
  );
  relClose('solver transfer continues finite n_k as q proportional to k squared',
    finiteOccupationQ[0], 0.000625, 1e-12);
  const boseLowQ = interpolateQ(
    [0.1, 0.2, 0.3], [1, 1, 1], shiftedLowGrid, { lower: 'power-law' },
  );
  relClose('solver transfer continues mu=0 Bose q as constant', boseLowQ[0], 1, 1e-12);

  const topHat = PRESETS.find((preset) => preset.key === 'nk_top_hat')!.load();
  const belowHat = topHat.raw.k_um_inv.findIndex((k) => k >= 1);
  const aboveHat = topHat.raw.k_um_inv.findIndex((k) => k >= 2.3);
  relClose('n_k top-hat is constant below k_p',
    topHat.raw.values[belowHat], topHat.raw.values[0], 1e-12);
  check('n_k top-hat vanishes above k_p', topHat.raw.values[aboveHat] === 0,
    `n_k=${topHat.raw.values[aboveHat]}`);

  // Nk_over_N convention: scale invariance — multiplying the column by 1000
  // must not change q at all.
  const base = profiles[0];
  const a = prepareSpectrum({
    k_um_inv: base.raw_k, values: base.raw_q,
    convention: 'Nk_over_N', label: 'a', source: 'preset', warnings: [],
  });
  const b = prepareSpectrum({
    k_um_inv: base.raw_k, values: base.raw_q.map((v) => v * 1000),
    convention: 'Nk_over_N', label: 'b', source: 'preset', warnings: [],
  });
  let worst = 0;
  for (let i = 0; i < a.q.length; i++) worst = Math.max(worst, Math.abs(a.q[i] - b.q[i]));
  check('Nk_over_N is scale invariant', worst < 1e-15, `max |Δq|=${worst.toExponential(2)}`);

  // The two conventions must give different answers — no silent guessing.
  const asNk = prepareSpectrum({
    k_um_inv: base.raw_k, values: base.raw_q,
    convention: 'n_k', label: 'c', source: 'preset', warnings: [],
  });
  const dA = computeDescriptors(a.k, a.q);
  const dN = computeDescriptors(asNk.k, asNk.q);
  check('conventions are not interchangeable',
    Math.abs(dA.kp0_um_inv / dN.kp0_um_inv - 1) > 0.01,
    `k_p ${dA.kp0_um_inv.toFixed(4)} vs ${dN.kp0_um_inv.toFixed(4)} μm⁻¹`);
}

section('Trajectory export');
{
  const exported = exportTrajectory(
    Float64Array.from([1, 2]),
    [
      { t_s: 0, q: [0.25, 0.75] },
      { t_s: 0.5, q: [0.5, 0.5] },
    ],
    3,
  );
  const lines = exported.csv.split('\n');
  check('trajectory export has k,n_k,time header', lines[0] === 'k_um_inv,n_k,time_s', lines[0]);
  check('trajectory export emits every k point at every time', exported.rows === 4 && exported.curves === 2,
    `rows=${exported.rows} curves=${exported.curves}`);
  const firstNk = Number(lines[1].split(',')[1]);
  relClose('trajectory n_k matches plotted occupation conversion', firstNk,
    0.25 * 2 * Math.PI ** 2 * 3, 1e-9);
}

// -------------------------------------------------------- peak detection ---

section('Peak detection');
{
  check('a one-point ripple is not a separate mode',
    countModes(Float64Array.from([0, 0.2, 0.20001, 0.2, 1, 0.5, 0])) === 1,
    'requires 1% peak prominence');
  check('a distinct secondary peak remains a mode',
    countModes(Float64Array.from([0, 0.3, 0.5, 0.1, 1, 0.5, 0])) === 2,
    'prominent peaks are retained');
}

// ---------------------------------------------------- parameter modes ---

section('Parameter modes');
{
  const d = computeDescriptors(
    Float64Array.from(profiles[0].raw_k),
    Float64Array.from(profiles[0].raw_q),
  );
  const N = 1e5;
  const n = META.density_um3;
  const V = N / n;

  const nva = derivePhysics(
    { mode: 'known_NVa', speciesKey: 'K39', N, V_um3: V, density_um3: null, a_a0: 50, dt_measured_s: null },
    d,
  );
  relClose('mode N,V,a → n', nva.density_um3!, n, 1e-12);
  relClose('mode N,V,a → na', nva.na_um2!, META.na_ref_um2, 1e-12);
  check('mode N,V,a enables quantum', nva.quantumAvailable, 'quantumAvailable');

  const na = derivePhysics(
    { mode: 'known_na', speciesKey: 'K39', N: null, V_um3: null, density_um3: n, a_a0: 50, dt_measured_s: null },
    d,
  );
  relClose('mode n,a → na', na.na_um2!, META.na_ref_um2, 1e-12);

  // Inverse mode: feeding back the formula's own Δt must recover na, then n, V.
  const dtRef = predictDeltaT(d, META.na_ref_um2);
  const inv = derivePhysics(
    { mode: 'measured_dt', speciesKey: 'K39', N, V_um3: null, density_um3: null, a_a0: 50, dt_measured_s: dtRef },
    d,
  );
  relClose('mode Δt → na', inv.na_um2!, META.na_ref_um2, 1e-12);
  relClose('mode Δt + a → n', inv.density_um3!, n, 1e-12);
  relClose('mode Δt + a + N → V', inv.V_um3!, V, 1e-12);

  const naOnly = derivePhysics(
    { mode: 'measured_dt', speciesKey: 'K39', N: null, V_um3: null, density_um3: null, a_a0: null, dt_measured_s: dtRef },
    d,
  );
  check('na-only mode invents neither n nor V',
    naOnly.density_um3 === null && naOnly.V_um3 === null,
    `n=${naOnly.density_um3} V=${naOnly.V_um3}`);
  check('na-only mode disables quantum', !naOnly.quantumAvailable, 'quantumAvailable=false');

  const invalidA = derivePhysics(
    { mode: 'known_na', speciesKey: 'K39', N: null, V_um3: null, density_um3: n, a_a0: 0, dt_measured_s: null },
    d,
  );
  check('non-positive a is rejected before a run',
    invalidA.na_um2 === null && invalidA.notes.some((note) => note.includes('must be positive')),
    invalidA.notes.join('; '));

  const refinedNa = META.na_ref_um2 * 1.08;
  const refined = derivePhysics(
    { mode: 'measured_dt', speciesKey: 'K39', N, V_um3: null, density_um3: null, a_a0: 50, dt_measured_s: dtRef, na_override_um2: refinedNa },
    d,
  );
  relClose('measured mode adopts a simulation-refined na', refined.na_um2!, refinedNa, 1e-14);
  relClose('refined na propagates to density', refined.density_um3!, n * 1.08, 1e-12);
}

// --------------------------------------------------------- WKE solver ---

section('WKE solver vs Python');

const HALF_TIME_TOL = 0.01; // 1% requirement
const timings: Array<{ key: string; kernel: KernelType; ms: number; steps: number }> = [];

for (const p of profiles) {
  const kFix = Float64Array.from(p.raw_k);
  const qFix = Float64Array.from(p.raw_q);
  const qSolver = normalizeQ(interpolateQ(p.raw_k, p.raw_q, kSolver), kSolver);
  const f0 = buildInitialF(qSolver, kSolver, META.density_um3);

  // The solver's own peak estimator, applied to the occupation, must agree with
  // the descriptor estimator applied to q.
  const kpF = peakMomentumFromF(kSolver, f0);
  relClose(`${p.key}: k_p,0 from f == from q`, kpF, peakMomentum(kFix, qFix), 1e-10);
  relClose(`${p.key}: k_p,0 from f vs Python`, kpF, p.kp0_um_inv, 1e-10);

  // Density reconstruction: (1/2π²)∫k²f dk must return n exactly.
  const kk = new Float64Array(kSolver.length);
  for (let i = 0; i < kk.length; i++) kk[i] = kSolver[i] ** 2 * f0[i];
  relClose(`${p.key}: density from f`, trapz(kk, kSolver) / (2 * Math.PI ** 2), META.density_um3, 1e-12);

  for (const kernel of ['classical', 'quantum'] as KernelType[]) {
    const traj = kernel === 'classical' ? p.trajectory_classical : p.trajectory_quantum;
    const res = runWKE({
      kernel, geom,
      t0_s: META.t0_s, xi_um: META.xi_um,
      kp0_um_inv: kpF, f0,
      tauMax: 400, rtol: 1e-7, atol: 1e-10,
      tauEval: traj.t_s.map((t: number) => t / META.t0_s),
    });
    timings.push({ key: p.key, kernel, ms: res.wallTime_ms, steps: res.nSteps });

    const want = kernel === 'classical' ? p.dt_half_classical_s : p.dt_half_quantum_s;
    check(`${p.key}: ${kernel} reached k_p,0/2`, res.reachedHalf, `tau=${res.tauHalf}`);
    relClose(`${p.key}: ${kernel} Δt₁ᐟ₂`, res.dtHalf_s!, want, HALF_TIME_TOL);

    // Stage snapshots must exist and be monotone in time.
    const stages = res.snapshots.filter((s) => s.stage !== 'sample').map((s) => s.stage);
    check(`${p.key}: ${kernel} stage snapshots`,
      ['initial', '0.90', '0.75', '0.50'].every((s) => stages.includes(s)),
      stages.join(' '));

    // k_p(t) checkpoints: the browser dense output evaluated at exactly the
    // times scipy reported, so no interpolation enters the comparison.
    let worst = 0;
    let checked = 0;
    for (let i = 0; i < res.evalTrack.kp.length && i < traj.kp.length; i++) {
      worst = Math.max(worst, Math.abs(res.evalTrack.kp[i] / traj.kp[i] - 1));
      checked++;
    }
    check(`${p.key}: ${kernel} k_p(t) checkpoints (${checked})`,
      checked >= 20 && worst < 2e-3, `max rel=${worst.toExponential(2)}`);
  }
}

section('Configurable stop target');
{
  const p = profiles[0];
  const qSolver = normalizeQ(interpolateQ(p.raw_k, p.raw_q, kSolver), kSolver);
  const f0 = buildInitialF(qSolver, kSolver, META.density_um3);
  const kp0 = peakMomentumFromF(kSolver, f0);
  const target = 0.8;
  const res = runWKE({
    kernel: 'classical', geom, t0_s: META.t0_s, xi_um: META.xi_um,
    kp0_um_inv: kp0, f0, tauMax: 400, rtol: 1e-7, atol: 1e-10,
    stopKpFraction: target,
  });
  check('custom target is reached', res.reachedHalf, `tau=${res.tauHalf}`);
  relClose('custom target stops at requested k_p ratio',
    res.snapshots.at(-1)!.kp_um_inv / kp0, target, 2e-4);
  check('custom target is earlier than half-time',
    res.dtHalf_s! < p.dt_half_classical_s,
    `${res.dtHalf_s} s vs ${p.dt_half_classical_s} s`);
}

// Classical dynamics depend on n and a only through na: two (n, a) pairs with
// the same product must give the same half-time.
section('Classical na-invariance');
{
  const p = profiles[0];
  const results: number[] = [];
  for (const factor of [1, 4]) {
    const n = META.density_um3 * factor;
    const a = META.scattering_length_a0 / factor;
    const s = computeScales(n, a, SPECIES.K39);
    const kLoc = Float64Array.from(pGrid, (pp) => pp / s.xi_um);
    const g = buildGeometry(pGrid, P_MAX / Math.SQRT2, s.ncal, NQ_LOW, NQ_HIGH);
    const q = normalizeQ(interpolateQ(p.raw_k, p.raw_q, kLoc), kLoc);
    const f0 = buildInitialF(q, kLoc, n);
    const res = runWKE({
      kernel: 'classical', geom: g, t0_s: s.t0_s, xi_um: s.xi_um,
      kp0_um_inv: peakMomentumFromF(kLoc, f0), f0, tauMax: 400, rtol: 1e-7, atol: 1e-10,
    });
    results.push(res.dtHalf_s!);
  }
  relClose('classical Δt₁ᐟ₂ depends on n, a only via na', results[1], results[0], 2e-3);
}

// Weak coupling used to leave only k_max ~= 3.49 um^-1 for this case.  The
// direct cascade then struck the collision cutoff and produced O(1) moment
// drift even though the initial spectrum itself had full grid coverage.
section('Weak-coupling grid headroom');
{
  const density = 400_000 / 140_000;
  const scales = computeScales(density, 8, SPECIES.K39);
  const pMax = solverPMax(scales.xi_um);
  const pWeak = logarithmicGrid(P_MIN, pMax, N_GRID);
  const kWeak = Float64Array.from(pWeak, (p) => p / scales.xi_um);
  const qRaw = Float64Array.from(kWeak, (k) => Math.exp(-0.5 * ((k - 1.5) / 0.21) ** 2));
  const q = normalizeQ(qRaw, kWeak);
  const f0 = buildInitialF(q, kWeak, density);
  const weakGeom = buildGeometry(pWeak, pMax / Math.SQRT2, scales.ncal, NQ_LOW, NQ_HIGH);
  const res = runWKE({
    kernel: 'quantum', geom: weakGeom, t0_s: scales.t0_s, xi_um: scales.xi_um,
    kp0_um_inv: peakMomentumFromF(kWeak, f0), f0, tauMax: 400,
    rtol: 1e-7, atol: 1e-10,
  });
  check('weak-coupling quantum run reaches k_p,0/2', res.reachedHalf, `tau=${res.tauHalf}`);
  check('weak-coupling particle drift remains below 5%', res.maxDN < 0.05,
    `max drift=${(100 * res.maxDN).toFixed(3)}%`);
  check('weak-coupling energy drift remains below 5%', res.maxDE < 0.05,
    `max drift=${(100 * res.maxDE).toFixed(3)}%`);
}

// Continuing a finished run must reproduce a single longer run of the same
// total duration: resuming from finalF and integrating haltOnHalf:false for
// the remaining time should land on the same state as never having stopped.
section('Continue simulating (haltOnHalf resume)');
{
  const p = profiles[0];
  const qSolver = normalizeQ(interpolateQ(p.raw_k, p.raw_q, kSolver), kSolver);
  const f0 = buildInitialF(qSolver, kSolver, META.density_um3);
  const kp0 = peakMomentumFromF(kSolver, f0);

  // Segment 1: a normal run to the half-crossing, exactly as "Run" does.
  const segment1 = runWKE({
    kernel: 'classical', geom, t0_s: META.t0_s, xi_um: META.xi_um,
    kp0_um_inv: kp0, f0, tauMax: 400, rtol: 1e-7, atol: 1e-10,
  });
  check('segment 1 reaches k_p,0/2', segment1.reachedHalf, `tau=${segment1.tauHalf}`);

  const totalTau = segment1.finalTau * 2; // "Continue" doubles the elapsed time
  const extraTau = totalTau - segment1.finalTau;

  // Segment 2: resume from segment 1's raw end state, exactly as 'continue' does.
  const segment2 = runWKE({
    kernel: 'classical', geom, t0_s: META.t0_s, xi_um: META.xi_um,
    kp0_um_inv: kp0, f0: segment1.finalF, tauMax: extraTau,
    rtol: 1e-7, atol: 1e-10, haltOnHalf: false,
  });

  // Reference: a single uninterrupted run of the same total duration.
  const reference = runWKE({
    kernel: 'classical', geom, t0_s: META.t0_s, xi_um: META.xi_um,
    kp0_um_inv: kp0, f0, tauMax: totalTau, rtol: 1e-7, atol: 1e-10, haltOnHalf: false,
  });

  relClose('resumed run reaches the same k_p as an uninterrupted run',
    segment2.kpTrack.kp.at(-1)!, reference.kpTrack.kp.at(-1)!, 5e-4);

  const qReference = reference.snapshots.at(-1)!.q;
  const qResumed = segment2.snapshots.at(-1)!.q;
  let worstQ = 0;
  for (let i = 0; i < qReference.length; i++) {
    if (qReference[i] > 1e-6) worstQ = Math.max(worstQ, Math.abs(qResumed[i] / qReference[i] - 1));
  }
  check('resumed run reproduces the spectrum shape', worstQ < 1e-2, `max rel=${worstQ.toExponential(2)}`);
  // A tight q-shape match isn't expected bit-for-bit: resuming restarts the
  // adaptive step-size controller from scratch at the handoff state, so the
  // two paths take a slightly different sequence of steps forward even though
  // both satisfy the same rtol locally. k_p, the quantity that actually
  // matters for Δt₁ᐟ₂, is unaffected (checked above to 1e-8).
}

// ------------------------------------------------------------- report ---

console.log(rows.join('\n'));
console.log('');
console.log('Solver timings (Node, single thread):');
for (const t of timings) {
  console.log(`  ${t.key.padEnd(20)} ${t.kernel.padEnd(10)} ${(t.ms / 1000).toFixed(2)} s  ${t.steps} steps`);
}
console.log('');
console.log(`${passed} passed, ${failures.length} failed`);
if (failures.length > 0) {
  console.log('');
  for (const f of failures) console.log(`  FAIL  ${f}`);
  process.exit(1);
}
